/* automatically generated by rust-bindgen 0.71.1 */

pub const CONFIG_ARM_HIKEY_OUTSTANDING_PREFETCHERS: u32 = 0;
pub const CONFIG_ARM_HIKEY_PREFETCHER_STRIDE: u32 = 0;
pub const CONFIG_ARM_HIKEY_PREFETCHER_NPFSTRM: u32 = 0;
pub const CONFIG_ARCH_AARCH64: u32 = 1;
pub const CONFIG_ARCH_ARM: u32 = 1;
pub const CONFIG_WORD_SIZE: u32 = 64;
pub const CONFIG_PLAT_QEMU_ARM_VIRT: u32 = 1;
pub const CONFIG_ARM_CORTEX_A53: u32 = 1;
pub const CONFIG_ARCH_ARM_V8A: u32 = 1;
pub const CONFIG_KERNEL_MCS: u32 = 1;
pub const CONFIG_ARM_PA_SIZE_BITS_40: u32 = 1;
pub const CONFIG_ARM_ICACHE_VIPT: u32 = 1;
pub const CONFIG_ARM_HYPERVISOR_SUPPORT: u32 = 1;
pub const CONFIG_AARCH64_USER_CACHE_ENABLE: u32 = 1;
pub const CONFIG_ARM_TLS_REG_TPIDRU: u32 = 1;
pub const CONFIG_L1_CACHE_LINE_SIZE_BITS: u32 = 6;
pub const CONFIG_HAVE_FPU: u32 = 1;
pub const CONFIG_PADDR_USER_DEVICE_TOP: u64 = 1099511627776;
pub const CONFIG_ROOT_CNODE_SIZE_BITS: u32 = 12;
pub const CONFIG_BOOT_THREAD_TIME_SLICE: u32 = 5;
pub const CONFIG_RETYPE_FAN_OUT_LIMIT: u32 = 256;
pub const CONFIG_MAX_NUM_WORK_UNITS_PER_PREEMPTION: u32 = 100;
pub const CONFIG_RESET_CHUNK_BITS: u32 = 8;
pub const CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS: u32 = 230;
pub const CONFIG_FASTPATH: u32 = 1;
pub const CONFIG_NUM_DOMAINS: u32 = 1;
pub const CONFIG_NUM_PRIORITIES: u32 = 256;
pub const CONFIG_MAX_NUM_NODES: u32 = 2;
pub const CONFIG_ENABLE_MULTIKERNEL_SUPPORT: u32 = 1;
pub const CONFIG_KERNEL_STACK_BITS: u32 = 12;
pub const CONFIG_DEBUG_BUILD: u32 = 1;
pub const CONFIG_PRINTING: u32 = 1;
pub const CONFIG_NO_BENCHMARKS: u32 = 1;
pub const CONFIG_MAX_NUM_TRACE_POINTS: u32 = 0;
pub const CONFIG_IRQ_REPORTING: u32 = 1;
pub const CONFIG_COLOUR_PRINTING: u32 = 1;
pub const CONFIG_USER_STACK_TRACE_LENGTH: u32 = 16;
pub const CONFIG_KERNEL_OPT_LEVEL_O2: u32 = 1;
pub const CONFIG_KERNEL_OPTIMISATION_CLONE_FUNCTIONS: u32 = 1;
pub const CONFIG_KERNEL_WCET_SCALE: u32 = 1;
pub const CONFIG_KERNEL_STATIC_MAX_PERIOD_US: u32 = 0;
pub const CONFIG_EXPORT_PCNT_USER: u32 = 1;
pub const CONFIG_EXPORT_PTMR_USER: u32 = 1;
pub const CONFIG_LIB_SEL4_INLINE_INVOCATIONS: u32 = 1;
pub const CONFIG_LIB_SEL4_PRINT_INVOCATION_ERRORS: u32 = 0;
pub const seL4_True: u32 = 1;
pub const seL4_False: u32 = 0;
pub const seL4_DataFault: u32 = 0;
pub const seL4_InstructionFault: u32 = 1;
pub const seL4_PageBits: u32 = 12;
pub const seL4_LargePageBits: u32 = 21;
pub const seL4_HugePageBits: u32 = 30;
pub const seL4_SlotBits: u32 = 5;
pub const seL4_TCBBits: u32 = 11;
pub const seL4_EndpointBits: u32 = 4;
pub const seL4_NotificationBits: u32 = 6;
pub const seL4_ReplyBits: u32 = 5;
pub const seL4_PageTableBits: u32 = 12;
pub const seL4_PageTableEntryBits: u32 = 3;
pub const seL4_PageTableIndexBits: u32 = 9;
pub const seL4_NumASIDPoolsBits: u32 = 7;
pub const seL4_ASIDPoolBits: u32 = 12;
pub const seL4_ASIDPoolIndexBits: u32 = 9;
pub const seL4_IOPageTableBits: u32 = 12;
pub const seL4_WordSizeBits: u32 = 3;
pub const seL4_VSpaceEntryBits: u32 = 3;
pub const seL4_VSpaceBits: u32 = 13;
pub const seL4_VSpaceIndexBits: u32 = 10;
pub const seL4_ARM_VCPUBits: u32 = 12;
pub const seL4_VCPUBits: u32 = 12;
pub const seL4_MinUntypedBits: u32 = 4;
pub const seL4_MaxUntypedBits: u32 = 47;
pub const seL4_FastMessageRegisters: u32 = 4;
pub const seL4_IPCBufferSizeBits: u32 = 10;
pub const seL4_UserTop: u64 = 1099511627775;
pub type seL4_Int8 = ::std::os::raw::c_schar;
pub type seL4_Uint8 = ::std::os::raw::c_uchar;
pub type seL4_Int16 = ::std::os::raw::c_short;
pub type seL4_Uint16 = ::std::os::raw::c_ushort;
pub type seL4_Int32 = ::std::os::raw::c_int;
pub type seL4_Uint32 = ::std::os::raw::c_uint;
pub type seL4_Int64 = ::std::os::raw::c_long;
pub type seL4_Uint64 = ::std::os::raw::c_ulong;
pub type seL4_Bool = seL4_Int8;
pub type seL4_Word = seL4_Uint64;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_X0: seL4_UnknownSyscall_Msg = 0;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_X1: seL4_UnknownSyscall_Msg = 1;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_X2: seL4_UnknownSyscall_Msg = 2;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_X3: seL4_UnknownSyscall_Msg = 3;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_X4: seL4_UnknownSyscall_Msg = 4;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_X5: seL4_UnknownSyscall_Msg = 5;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_X6: seL4_UnknownSyscall_Msg = 6;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_X7: seL4_UnknownSyscall_Msg = 7;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_FaultIP: seL4_UnknownSyscall_Msg = 8;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_SP: seL4_UnknownSyscall_Msg = 9;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_LR: seL4_UnknownSyscall_Msg = 10;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_SPSR: seL4_UnknownSyscall_Msg = 11;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_Syscall: seL4_UnknownSyscall_Msg = 12;
pub const seL4_UnknownSyscall_Msg_seL4_UnknownSyscall_Length: seL4_UnknownSyscall_Msg = 13;
pub const seL4_UnknownSyscall_Msg__enum_pad_seL4_UnknownSyscall_Msg: seL4_UnknownSyscall_Msg =
    9223372036854775807;
pub type seL4_UnknownSyscall_Msg = ::std::os::raw::c_ulong;
pub const seL4_UserException_Msg_seL4_UserException_FaultIP: seL4_UserException_Msg = 0;
pub const seL4_UserException_Msg_seL4_UserException_SP: seL4_UserException_Msg = 1;
pub const seL4_UserException_Msg_seL4_UserException_SPSR: seL4_UserException_Msg = 2;
pub const seL4_UserException_Msg_seL4_UserException_Number: seL4_UserException_Msg = 3;
pub const seL4_UserException_Msg_seL4_UserException_Code: seL4_UserException_Msg = 4;
pub const seL4_UserException_Msg_seL4_UserException_Length: seL4_UserException_Msg = 5;
pub const seL4_UserException_Msg__enum_pad_seL4_UserException_Msg: seL4_UserException_Msg =
    9223372036854775807;
pub type seL4_UserException_Msg = ::std::os::raw::c_ulong;
pub const seL4_VMFault_Msg_seL4_VMFault_IP: seL4_VMFault_Msg = 0;
pub const seL4_VMFault_Msg_seL4_VMFault_Addr: seL4_VMFault_Msg = 1;
pub const seL4_VMFault_Msg_seL4_VMFault_PrefetchFault: seL4_VMFault_Msg = 2;
pub const seL4_VMFault_Msg_seL4_VMFault_FSR: seL4_VMFault_Msg = 3;
pub const seL4_VMFault_Msg_seL4_VMFault_Length: seL4_VMFault_Msg = 4;
pub const seL4_VMFault_Msg__enum_pad_seL4_VMFault_Msg: seL4_VMFault_Msg = 9223372036854775807;
pub type seL4_VMFault_Msg = ::std::os::raw::c_ulong;
pub const seL4_VGICMaintenance_Msg_seL4_VGICMaintenance_IDX: seL4_VGICMaintenance_Msg = 0;
pub const seL4_VGICMaintenance_Msg_seL4_VGICMaintenance_Length: seL4_VGICMaintenance_Msg = 1;
pub const seL4_VGICMaintenance_Msg__enum_pad_seL4_VGICMaintenance_Msg: seL4_VGICMaintenance_Msg =
    9223372036854775807;
pub type seL4_VGICMaintenance_Msg = ::std::os::raw::c_ulong;
pub const seL4_VPPIEvent_Msg_seL4_VPPIEvent_IRQ: seL4_VPPIEvent_Msg = 0;
pub const seL4_VPPIEvent_Msg_seL4_VPPIEvent_Length: seL4_VPPIEvent_Msg = 1;
pub const seL4_VPPIEvent_Msg__enum_pad_seL4_VPPIEvent_Msg: seL4_VPPIEvent_Msg = 9223372036854775807;
pub type seL4_VPPIEvent_Msg = ::std::os::raw::c_ulong;
pub const seL4_VCPUFault_Msg_seL4_VCPUFault_HSR: seL4_VCPUFault_Msg = 0;
pub const seL4_VCPUFault_Msg_seL4_VCPUFault_Length: seL4_VCPUFault_Msg = 1;
pub const seL4_VCPUFault_Msg__enum_pad_seL4_VCPUFault_Msg: seL4_VCPUFault_Msg = 9223372036854775807;
pub type seL4_VCPUFault_Msg = ::std::os::raw::c_ulong;
pub const seL4_VCPUReg_seL4_VCPUReg_SCTLR: seL4_VCPUReg = 0;
pub const seL4_VCPUReg_seL4_VCPUReg_CPACR: seL4_VCPUReg = 1;
pub const seL4_VCPUReg_seL4_VCPURegSaveRange_start: seL4_VCPUReg = 2;
pub const seL4_VCPUReg_seL4_VCPUReg_TTBR0: seL4_VCPUReg = 2;
pub const seL4_VCPUReg_seL4_VCPUReg_TTBR1: seL4_VCPUReg = 3;
pub const seL4_VCPUReg_seL4_VCPUReg_TCR: seL4_VCPUReg = 4;
pub const seL4_VCPUReg_seL4_VCPUReg_MAIR: seL4_VCPUReg = 5;
pub const seL4_VCPUReg_seL4_VCPUReg_AMAIR: seL4_VCPUReg = 6;
pub const seL4_VCPUReg_seL4_VCPUReg_CIDR: seL4_VCPUReg = 7;
pub const seL4_VCPUReg_seL4_VCPUReg_ACTLR: seL4_VCPUReg = 8;
pub const seL4_VCPUReg_seL4_VCPUReg_AFSR0: seL4_VCPUReg = 9;
pub const seL4_VCPUReg_seL4_VCPUReg_AFSR1: seL4_VCPUReg = 10;
pub const seL4_VCPUReg_seL4_VCPUReg_ESR: seL4_VCPUReg = 11;
pub const seL4_VCPUReg_seL4_VCPUReg_FAR: seL4_VCPUReg = 12;
pub const seL4_VCPUReg_seL4_VCPUReg_ISR: seL4_VCPUReg = 13;
pub const seL4_VCPUReg_seL4_VCPUReg_VBAR: seL4_VCPUReg = 14;
pub const seL4_VCPUReg_seL4_VCPUReg_TPIDR_EL1: seL4_VCPUReg = 15;
pub const seL4_VCPUReg_seL4_VCPUReg_VMPIDR_EL2: seL4_VCPUReg = 16;
pub const seL4_VCPUReg_seL4_VCPUReg_SP_EL1: seL4_VCPUReg = 17;
pub const seL4_VCPUReg_seL4_VCPUReg_ELR_EL1: seL4_VCPUReg = 18;
pub const seL4_VCPUReg_seL4_VCPUReg_SPSR_EL1: seL4_VCPUReg = 19;
pub const seL4_VCPUReg_seL4_VCPURegSaveRange_end: seL4_VCPUReg = 19;
pub const seL4_VCPUReg_seL4_VCPUReg_CNTV_CTL: seL4_VCPUReg = 20;
pub const seL4_VCPUReg_seL4_VCPUReg_CNTV_CVAL: seL4_VCPUReg = 21;
pub const seL4_VCPUReg_seL4_VCPUReg_CNTVOFF: seL4_VCPUReg = 22;
pub const seL4_VCPUReg_seL4_VCPUReg_CNTKCTL_EL1: seL4_VCPUReg = 23;
pub const seL4_VCPUReg_seL4_VCPUReg_Num: seL4_VCPUReg = 24;
pub const seL4_VCPUReg__enum_pad_seL4_VCPUReg: seL4_VCPUReg = 9223372036854775807;
pub type seL4_VCPUReg = ::std::os::raw::c_ulong;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_FaultIP: seL4_TimeoutReply_Msg = 0;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_SP: seL4_TimeoutReply_Msg = 1;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_SPSR_EL1: seL4_TimeoutReply_Msg = 2;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X0: seL4_TimeoutReply_Msg = 3;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X1: seL4_TimeoutReply_Msg = 4;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X2: seL4_TimeoutReply_Msg = 5;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X3: seL4_TimeoutReply_Msg = 6;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X4: seL4_TimeoutReply_Msg = 7;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X5: seL4_TimeoutReply_Msg = 8;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X6: seL4_TimeoutReply_Msg = 9;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X7: seL4_TimeoutReply_Msg = 10;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X8: seL4_TimeoutReply_Msg = 11;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X16: seL4_TimeoutReply_Msg = 12;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X17: seL4_TimeoutReply_Msg = 13;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X18: seL4_TimeoutReply_Msg = 14;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X29: seL4_TimeoutReply_Msg = 15;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X30: seL4_TimeoutReply_Msg = 16;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X9: seL4_TimeoutReply_Msg = 17;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X10: seL4_TimeoutReply_Msg = 18;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X11: seL4_TimeoutReply_Msg = 19;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X12: seL4_TimeoutReply_Msg = 20;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X13: seL4_TimeoutReply_Msg = 21;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X14: seL4_TimeoutReply_Msg = 22;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X15: seL4_TimeoutReply_Msg = 23;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X19: seL4_TimeoutReply_Msg = 24;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X20: seL4_TimeoutReply_Msg = 25;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X21: seL4_TimeoutReply_Msg = 26;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X22: seL4_TimeoutReply_Msg = 27;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X23: seL4_TimeoutReply_Msg = 28;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X24: seL4_TimeoutReply_Msg = 29;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X25: seL4_TimeoutReply_Msg = 30;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X26: seL4_TimeoutReply_Msg = 31;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X27: seL4_TimeoutReply_Msg = 32;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_X28: seL4_TimeoutReply_Msg = 33;
pub const seL4_TimeoutReply_Msg_seL4_TimeoutReply_Length: seL4_TimeoutReply_Msg = 34;
pub const seL4_TimeoutReply_Msg__enum_pad_seL4_TimeoutReply_Msg: seL4_TimeoutReply_Msg =
    9223372036854775807;
pub type seL4_TimeoutReply_Msg = ::std::os::raw::c_ulong;
pub const seL4_Timeout_Msg_seL4_Timeout_Data: seL4_Timeout_Msg = 0;
pub const seL4_Timeout_Msg_seL4_Timeout_Consumed: seL4_Timeout_Msg = 1;
pub const seL4_Timeout_Msg_seL4_Timeout_Length: seL4_Timeout_Msg = 2;
pub const seL4_Timeout_Msg__enum_pad_seL4_Timeout_Msg: seL4_Timeout_Msg = 9223372036854775807;
pub type seL4_Timeout_Msg = ::std::os::raw::c_ulong;
pub type seL4_ARM_VSpace = seL4_CPtr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct seL4_UserContext_ {
    pub pc: seL4_Word,
    pub sp: seL4_Word,
    pub spsr: seL4_Word,
    pub x0: seL4_Word,
    pub x1: seL4_Word,
    pub x2: seL4_Word,
    pub x3: seL4_Word,
    pub x4: seL4_Word,
    pub x5: seL4_Word,
    pub x6: seL4_Word,
    pub x7: seL4_Word,
    pub x8: seL4_Word,
    pub x16: seL4_Word,
    pub x17: seL4_Word,
    pub x18: seL4_Word,
    pub x29: seL4_Word,
    pub x30: seL4_Word,
    pub x9: seL4_Word,
    pub x10: seL4_Word,
    pub x11: seL4_Word,
    pub x12: seL4_Word,
    pub x13: seL4_Word,
    pub x14: seL4_Word,
    pub x15: seL4_Word,
    pub x19: seL4_Word,
    pub x20: seL4_Word,
    pub x21: seL4_Word,
    pub x22: seL4_Word,
    pub x23: seL4_Word,
    pub x24: seL4_Word,
    pub x25: seL4_Word,
    pub x26: seL4_Word,
    pub x27: seL4_Word,
    pub x28: seL4_Word,
    pub tpidr_el0: seL4_Word,
    pub tpidrro_el0: seL4_Word,
}
pub type seL4_UserContext = seL4_UserContext_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct seL4_ARM_SMCContext_ {
    pub x0: seL4_Word,
    pub x1: seL4_Word,
    pub x2: seL4_Word,
    pub x3: seL4_Word,
    pub x4: seL4_Word,
    pub x5: seL4_Word,
    pub x6: seL4_Word,
    pub x7: seL4_Word,
}
pub type seL4_ARM_SMCContext = seL4_ARM_SMCContext_;
pub type seL4_ARM_Page = seL4_CPtr;
pub type seL4_ARM_PageTable = seL4_CPtr;
pub type seL4_ARM_PageDirectory = seL4_CPtr;
pub type seL4_ARM_ASIDControl = seL4_CPtr;
pub type seL4_ARM_ASIDPool = seL4_CPtr;
pub type seL4_ARM_VCPU = seL4_CPtr;
pub type seL4_ARM_IOSpace = seL4_CPtr;
pub type seL4_ARM_IOPageTable = seL4_CPtr;
pub type seL4_ARM_SIDControl = seL4_CPtr;
pub type seL4_ARM_SID = seL4_CPtr;
pub type seL4_ARM_CBControl = seL4_CPtr;
pub type seL4_ARM_CB = seL4_CPtr;
pub type seL4_ARM_SMC = seL4_CPtr;
pub type seL4_ARM_SGI_Signal = seL4_CPtr;
pub const seL4_ARM_VMAttributes_seL4_ARM_PageCacheable: seL4_ARM_VMAttributes = 1;
pub const seL4_ARM_VMAttributes_seL4_ARM_ParityEnabled: seL4_ARM_VMAttributes = 2;
pub const seL4_ARM_VMAttributes_seL4_ARM_Default_VMAttributes: seL4_ARM_VMAttributes = 3;
pub const seL4_ARM_VMAttributes_seL4_ARM_ExecuteNever: seL4_ARM_VMAttributes = 4;
pub const seL4_ARM_VMAttributes__enum_pad_seL4_ARM_VMAttributes: seL4_ARM_VMAttributes =
    9223372036854775807;
pub type seL4_ARM_VMAttributes = ::std::os::raw::c_ulong;
pub const seL4_ARM_CacheType_seL4_ARM_CacheI: seL4_ARM_CacheType = 1;
pub const seL4_ARM_CacheType_seL4_ARM_CacheD: seL4_ARM_CacheType = 2;
pub const seL4_ARM_CacheType_seL4_ARM_CacheID: seL4_ARM_CacheType = 3;
pub const seL4_ARM_CacheType__enum_pad_seL4_ARM_CacheType: seL4_ARM_CacheType = 9223372036854775807;
pub type seL4_ARM_CacheType = ::std::os::raw::c_ulong;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct seL4_KernelBootInfo {
    pub magic: seL4_Uint32,
    pub version: seL4_Uint8,
    pub _padding0: [seL4_Uint8; 3usize],
    pub root_task_entry: seL4_Uint64,
    pub root_task_pv_offset: seL4_Uint64,
    pub offset_of_memory_descriptors: seL4_Uint64,
    pub number_of_memory_descriptors: seL4_Uint32,
    pub _padding1: [seL4_Uint8; 28usize],
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct seL4_KernelBootMemoryDescriptor {
    pub base: seL4_Uint64,
    pub end: seL4_Uint64,
    pub kind: seL4_Uint8,
    pub _padding: [seL4_Uint8; 3usize],
}
