# Copyright 2021, Proofcraft Pty Ltd
# Copyright 2026, UNSW
#
# SPDX-License-Identifier: BSD-2-Clause

# Deploy default.xml to microkit-manifest after successful runs.

name: Deploy

on:
  push:
    # TEMP: remove
    branches: [main, julia/ci]
    paths-ignore:
      - '**.md'

  # allow manual trigger
  workflow_dispatch:

  # allow explicit trigger from other repos when dependencies have changed
  repository_dispatch:
    types: [deps-update]

jobs:
  code:
    name: Freeze Code
    runs-on: ubuntu-latest
    outputs:
      xml: ${{ steps.repo.outputs.xml }}
    steps:
      - id: repo
        uses: au-ts/seL4-ci-actions/repo-checkout@julia/microkit
        with:
          manifest_repo: au-ts/microkit-manifest
          manifest_branch: main
          manifest: main.xml
          use_venv: true

  sim:
    name: Simulation
    needs: code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        march: [aarch64, x86_64, riscv64]
        compiler: [gcc]
    steps:
      - uses: au-ts/seL4-ci-actions/microkit-sim@julia/microkit
        with:
          xml: ${{ needs.code.outputs.xml }}
          march: ${{ matrix.march }}
          compiler: ${{ matrix.compiler }}

  sdk-build:
    name: Build SDK (macOS, all targets)
    needs: code
    runs-on: [self-hosted, macos, ARM64]
    outputs:
      SDK_VERSION: ${{ steps.version.outputs.SDK_VERSION }}
    steps:
      - name: clean work dir (because self hosted) (this doesn't actually work)
        run: rm -rf ./*
      - name: Checkout code
        uses: au-ts/seL4-ci-actions/repo-checkout@julia/microkit
        with:
          xml: ${{ needs.code.outputs.xml }}
          # needed for reasons...
          manifest_repo: au-ts/microkit-manifest
          manifest_branch: main
          manifest: main.xml
          use_venv: true
      - name: Set version
        id: version
        run: |
          git fetch --tags --unshallow
          ./.github/sdk_version.sh
        working-directory: ./microkit/
      - name: Get Nix dependencies
        run: nix develop -c bash -c 'echo Hello World'
        working-directory: ./microkit/
      - name: Build SDK
        # TODO: remove boards
        run: nix develop --ignore-environment -c bash -c "python3 build_sdk.py --boards maaxboard --sel4=../seL4 --version ${{ env.SDK_VERSION }} --gcc-toolchain-prefix-x86_64 x86_64-elf --gcc-toolchain-prefix-riscv64 riscv64-none-elf --release-packaging"
        working-directory: ./microkit/
      - name: Upload SDK (macos-aarch64)
        uses: actions/upload-artifact@v4
        with:
          name: microkit-sdk-${{ env.SDK_VERSION }}-macos-aarch64
          path: microkit/release/microkit-sdk-${{ env.SDK_VERSION }}-macos-aarch64.tar.gz
      - name: Upload SDK (macos-x86-64)
        uses: actions/upload-artifact@v4
        with:
          name: microkit-sdk-${{ env.SDK_VERSION }}-macos-x86-64
          path: microkit/release/microkit-sdk-${{ env.SDK_VERSION }}-macos-x86-64.tar.gz
      - name: Upload SDK (linux-aarch64)
        uses: actions/upload-artifact@v4
        with:
          name: microkit-sdk-${{ env.SDK_VERSION }}-linux-aarch64
          path: microkit/release/microkit-sdk-${{ env.SDK_VERSION }}-linux-aarch64.tar.gz
      - name: Upload SDK (linux-x86-64)
        uses: actions/upload-artifact@v4
        with:
          name: microkit-sdk-${{ env.SDK_VERSION }}-linux-x86-64
          path: microkit/release/microkit-sdk-${{ env.SDK_VERSION }}-linux-x86-64.tar.gz

  # Not used for HW Run, just to confirm it builds on Linux outside of Nix.
  sdk-build-linux:
    name: Build SDK (Linux x86_64)
    runs-on: ubuntu-24.04
    needs: code
    steps:
      - name: Checkout code
        uses: au-ts/seL4-ci-actions/repo-checkout@julia/microkit
        with:
          xml: ${{ needs.code.outputs.xml }}
          # needed for reasons...
          manifest_repo: au-ts/microkit-manifest
          manifest_branch: main
          manifest: main.xml
          use_venv: true
      - name: Set version
        run: |
          git fetch --tags --unshallow
          ./.github/sdk_version.sh
        working-directory: ./microkit/
      - name: Install SDK dependencies
        run: ./.github/install_ubuntu_deps.sh
        working-directory: ./microkit/
      - name: Build SDK (x86-64)
        run: ./pyenv/bin/python build_sdk.py --sel4=../seL4 --version ${{ env.SDK_VERSION }}-linux-x86-64 --tool-target-triple="x86_64-unknown-linux-musl"
        working-directory: ./microkit/

  the_matrix:
    name: Matrix
    needs: sdk-build
    runs-on: ubuntu-latest
    outputs:
      gh_matrix: ${{ steps.matrix.outputs.gh_matrix }}
      test_cases: ${{ steps.matrix.outputs.test_cases }}
    steps:
      - name: Checkout code
        uses: au-ts/seL4-ci-actions/repo-checkout@julia/microkit
        with:
          xml: ${{ needs.code.outputs.xml }}
          # needed for reasons...
          manifest_repo: au-ts/microkit-manifest
          manifest_branch: main
          manifest: main.xml
          use_venv: true
      - id: matrix
        working-directory: ./microkit/
        run: |
          python3 build_sdk.py --sel4=../seL4 --matrix --boards maaxboard

  hw-run:
    name: HW Run
    if: ${{ github.repository_owner == 'au-ts' }}
    runs-on: ubuntu-latest
    needs: [sim, the_matrix, sdk-build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.the_matrix.outputs.gh_matrix) }}
    # do not run concurrently with other workflows, but do run concurrently in the build matrix
    concurrency: hw-run-${{ strategy.job-index }}
    env:
      SDK_VERSION: ${{ needs.sdk-build.outputs.SDK_VERSION }}
    steps:
      - name: Checkout code
        uses: au-ts/seL4-ci-actions/repo-checkout@julia/microkit
        with:
          xml: ${{ needs.code.outputs.xml }}
          # needed for reasons...
          manifest_repo: au-ts/microkit-manifest
          manifest_branch: main
          manifest: main.xml
          use_venv: true
      - name: Get machine queue
        uses: actions/checkout@v4
        with:
          repository: seL4/machine_queue
          path: machine_queue
      - name: Download microkit SDK
        uses: actions/download-artifact@v4
        with:
          name: microkit-sdk-${{ env.SDK_VERSION }}-linux-x86-64
      - name: Extract microkit SDK
        run: |
          tar xzf ./microkit-sdk-${{ env.SDK_VERSION }}-linux-x86-64.tar.gz
          export "MICROKIT_SDK=$(realpath ./microkit-sdk-${{ env.SDK_VERSION }}/)"
          stat "${MICROKIT_SDK}"
          echo "MICROKIT_SDK=${MICROKIT_SDK}" >> "${GITHUB_ENV}"
      - name: Run
        uses: au-ts/seL4-ci-actions/microkit-hw-run@julia/microkit
        with:
          platform: ${{ matrix.platform }}
          index: $${{ strategy.job-index }}
        env:
          TEST_CASES: ${{ needs.the_matrix.outputs.test_cases }}
          HW_SSH: ${{ secrets.HW_SSH }}

  deploy:
    name: Deploy manifest
    if: ${{ github.repository_owner == 'au-ts' }}
    runs-on: ubuntu-22.04
    needs: [code, hw-run]
    # needs: [code, hw-run, sdk-build-linux]
    steps:
    - name: Deploy
      uses: au-ts/seL4-ci-actions/manifest-deploy@julia/microkit
      with:
        xml: ${{ needs.code.outputs.xml }}
        manifest_repo: au-ts/microkit-manifest
        manifest_branch: main
      env:
        GH_SSH: ${{ secrets.CI_SSH }}
